config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete  '/logout',    to: 'sessions#destroy'

  resources :posts, only: [:new, :create, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	before_create :create_remember_token
	attr_accessor :remember_token

	has_many :posts	
	has_secure_password

	def new_token
		return SecureRandom.urlsafe_base64
	end

	private

		def create_remember_token
			token = new_token
			encrypted_token = Digest::SHA1.hexdigest(token.to_s)
			self.remember_token = encrypted_token
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	helper_method :current_user, :logged_in?
	
	def log_in(user)
		session[:user_id] = user.id
		user.remember_token = user.new_token
		cookies.permanent[:remember_token] = user.remember_token
		current_user=(user)
	end

	def sign_out
		@current_user = nil
  		cookies.signed[:remember_token] = nil
  		session.clear
  		redirect_to login_url
	end

	def logged_in?
		if current_user.nil? then
			flash[:error] = "You must be logged in to make posts"
			redirect_to login_url
		end
	end

	def current_user
		if session[:user_id]
			@current_user ||= User.find_by(id: session[:user_id])
		elsif cookies.signed[:remember_token]
			hash = Digest::SHA1.hexdigest(cookies.signed[:remember_token].to_s)
			current_user ||= User.find_by(hash)
		else
			nil
		end
	end

	def current_user=(user)
		@current_user = user
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action	:logged_in?, :only => [:new, :create]

	def new
		@post = Post.new
	end

	def create
		@post = Post.create(title: params[:post][:title], content: params[:post][:content], user_id: current_user.id)
		if @post.save
			redirect_to posts_path
		else
			flash.now[:danger] = "Couldn't save post!"
  			render 'new'
  		end
	end

	def index
		@posts = Post.all
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  
  end

  def create
	  	@user = User.find_by(email: params[:session][:email].downcase)
	  	if @user && @user.authenticate(params[:session][:password])
	  		log_in(@user)
    		redirect_to login_url
	  	else
	  		flash.now[:danger] = "Invalid email/password combination"
  			render 'new'
	  	end
  end

  def destroy
  	sign_out
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |message_type, message| %>
       <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <footer class="page-footer font-small blue pt-4 mt-4">
      <div class="col-md-6 col-md-offset-3">
      <div class="container-fluid text-center text-md-left">
        <div class="row">
            <% if current_user then %>
              Logged in as <%= current_user.name %>. <%= link_to "Log out", logout_path, :method => :delete %>
        </div>
        <div class="row">
          <%= link_to "New Post", new_post_path %>
          <% end %>
        </div>
        <%= link_to "View Posts", posts_path %>
      </div>
    </div>
    </footer>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
<h1>Title: <%= p.title %></h1>
<h5><%= p.content %></h5>
	<% if current_user %>
		<b>Author:</b> <%= User.find(p.user_id).name %>
	<% end %>
<hr />
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  	<h1>New Post</h1>
		<%= form_for :post, url: posts_path do |f| %>

		      <%= f.label :title %>
		      <%= f.text_field :title, class: 'form-control' %>

		      <%= f.label :content %>
		      <%= f.text_area :content, class: 'form-control' %>

		      <%= f.submit "Submit", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/static_pages/home.html.erb
<h1>Welcome to the Members-Only App</h1>

<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>